language: rust
group: deprecated-2017Q3
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      rust: stable
    - os: linux
      dist: trusty
      sudo: required
      rust: nightly
    - os: osx
      rust: stable
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --upgrade pip ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then admin/build-lcov ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then gem install coveralls-lcov ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then sudo apt-get install libclang-common-3.8-dev llvm-3.8-dev ; fi
script:
  - cargo build
  - RUST_BACKTRACE=1 cargo test
  - RUST_BACKTRACE=1 cargo test --features dangerous_configuration danger
  - cargo test --release --no-run
  - ./target/release/examples/bench
  - ( cd trytls && ./runme )
  - ( cd bogo && ./runme )
  - cargo build --no-default-features
  - cargo test --no-default-features --no-run
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then ./admin/coverage          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then coveralls-lcov final.info ; fi
